In [1]:
# lib imports
import pandas as pd
import csv
from datetime import datetime

In [2]:
data_location = "Data/Spotify_Data_Sample.csv"

## Initial Data Cleaning

In [3]:
df = pd.read_csv(data_location)
df.head()

C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1761512478.py:1: DtypeWarning: Columns (136,137,138,141,143,144,146,149,151,152,154,157,159,160,162,165,167,168,170,173,175,176,178,181,183,184,186,189,191,192,194,197,199,200,202,205,207,208,210,213,215,216,218,221,223,224,226,229,231,232,234,237,239,240,242,245,247,248,250,253,255,256,258,261,263,264,266,269,271,272,274,277,279,280,282,285,287,288,290,293,295,296,298,301,303,304,306,309,311,312,314,317,319,320,322,325,327,328,330,333,335,336,338,341,343,344,346,349,351,352,354,357,359,360,362,365,367,368,370,373,375,376,378,381,383,384,386,389,391,392,394,397,399,400,402,405,407,408,410,413,415,416,418,421,423,424,425,426,429,431,432,434,437,439,440,442,445,447,448,450,453,455,456,458,461,463,464,466,469,471,472,474,477,479,480,482,485,487,488,490,493,495,496,498,501,503,504,506,509,511,512,514,517,519,520,522,525,527,528,530,533,535,536,538,541,543,544,546,549,551,552,554,557,559,560,562,565,567,568,569,570,573,575,576,577,578,581,583,584,586,589,591,592,594,597,599,600,602,605,607,608,610,613,615,616,618,621,623,624,626,629,631,632,634,637,639,640,642,645,647,648,650,653,655,656,658,661,663,664,666,669,671,672,674,677,679,680,682,685,687,688,690,693,695,696,698,701,703,704,706,709,711,712,714,717,719,720,722,725,727,728,730,733,735,736,738,741,743,744,746,749,751,752,754,757,759,760,762,765,767,768,770,773,775,776,778,781,783,784,786,789,791,792,794,797,799,800,802,805,807,808,810,811,813,815,816,817,818,819,821,823,824,825,826,827,829,831,832,833,834,835,837,839,840,841,842,843,845,847,848,849,850,851,853,855,856,857,858,859,861,863,864,865,866,867,869,871,872,873,874,875,877,879,880,881,882,883,885,887,888,889,890,891,893,895,896,897,898,899,901,903,904,905,906,907,909,911,912,913,914,915,917,919,920,921,922,923,925,927,928,929,930,931,933,935,936,937,938,939,941,943,944,945,946,947,949,951,952,953,954,955,957,959,960,961,962,963,965,967,968,969,970,971,973,975,976,977,978,979,981,983,984,985,986,987,989,991,992,993,994,995,997,999,1000,1001,1002,1003,1005,1007,1008,1009,1010,1011,1013,1015,1016,1017,1018,1019,1021,1023,1024,1025,1026,1027,1029,1031,1032,1033,1034,1035,1037,1039,1040,1041,1042,1043,1045,1047,1048,1049,1050,1051,1053,1055,1056,1057,1058,1059,1061,1063,1064,1065,1066,1067,1069,1071,1072,1073,1074,1075,1077,1079,1080,1081,1082,1083,1085,1087,1088,1089,1090,1091,1093,1095,1096,1097,1098,1099,1101,1103,1104,1105,1106,1107,1109,1111,1112,1113,1114,1115,1117,1119,1120,1121,1122,1123,1125,1127,1128,1129,1130,1131,1133,1135,1136,1137,1138,1139,1141,1143,1144,1145,1146,1147,1149,1151,1152,1153,1154,1155,1157,1159,1160,1161,1162,1163,1165,1167,1168,1169,1170,1171,1173,1175,1176,1177,1178,1179,1181,1183,1184,1185,1186,1187,1189,1191,1192,1193,1194,1195,1197,1199,1200,1201,1202,1203,1205,1207,1208,1209,1210,1211,1213,1215,1216,1217,1218,1219,1221,1223,1224,1225,1226,1227,1229,1231,1232,1233,1234,1235,1237,1239,1240,1241,1242,1243,1245,1247,1248,1249,1250,1251,1253,1255,1256,1257,1258,1259,1261,1263,1264,1265,1266,1267,1269,1271,1272,1273,1274,1275,1277,1279,1280,1281,1282,1283,1285,1287,1288,1289,1290,1291,1293,1295,1296,1297,1298,1299,1301,1303,1304,1305,1306,1307,1309,1311,1312,1313,1314,1315,1317,1319,1320,1321,1322,1323,1325,1327,1328,1329,1330,1331,1333,1335,1336,1337,1338,1339,1341,1343,1344,1345,1346,1347,1349,1351,1352,1353,1354,1355,1357,1359,1360,1361,1362,1363,1365,1367,1368,1369,1370,1371,1373,1375,1376,1377,1378,1379,1381,1383,1384,1385,1386,1387,1389,1391,1392,1393,1394,1395,1397,1399,1400,1401,1402,1403,1405,1407,1408,1409,1410,1411,1413,1415,1416,1417,1418,1419,1421,1423,1424,1425,1426,1427,1429,1431,1432,1433,1434,1435,1437,1439,1440,1441,1442,1443,1445,1447,1448,1449,1450,1451,1453,1455,1456,1457,1458,1459,1461,1463,1464,1465,1466,1467,1469,1471,1472,1473,1474,1475,1477,1479,1480,1481,1482,1483,1485,1487,1488,1489,1490,1491,1493,1495,1496,1497,1498,1499,1501,1503,1504,1505,1506,1507,1509,1511,1512,1513,1514,1515,1517,1519,1520,1521,1522,1523,1528,1529,1530,1531,1536,1537,1538,1539,1544,1545,1546,1547,1552,1553,1554,1555,1560,1561,1562,1563,1568,1569,1570,1571,1576,1577,1578,1579,1584,1585,1586,1587,1592,1593,1594,1595,1600,1601,1602,1603,1608,1609,1610,1611,1616,1617,1618,1619,1624,1625,1626,1627,1632,1633,1634,1635,1640,1641,1642,1643,1648,1649,1650,1651,1656,1657,1658,1659,1664,1665,1666,1667,1672,1673,1674,1675,1680,1681,1682,1683,1688,1689,1690,1691,1696,1697,1698,1699,1704,1705,1706,1707,1712,1713,1714,1715,1720,1721,1722,1723,1728,1729,1730,1731,1736,1737,1738,1739,1744,1745,1746,1747,1752,1753,1754,1755,1760,1761,1762,1763,1768,1769,1770,1771,1776,1777,1778,1779,1784,1785,1786,1787,1792,1793,1794,1795,1800,1801,1802,1803,1808,1809,1810,1811,1816,1817,1818,1819,1824,1825,1826,1827,1832,1833,1834,1835,1840,1841,1842,1843,1848,1849,1850,1851,1856,1857,1858,1859,1864,1865,1866,1867,1872,1873,1874,1875,1880,1881,1882,1883,1888,1889,1890,1891,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1980,1981,1982,1983,1984,1986,1988,1989,1990,1991,1992,1994,1996,1997,1998,1999,2000,2002,2004,2005,2006,2007,2008,2010) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_location)

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks/0/pos,tracks/0/artist_name,tracks/0/track_uri,...,Unnamed: 2001,Unnamed: 2002,Unnamed: 2003,Unnamed: 2004,Unnamed: 2005,Unnamed: 2006,Unnamed: 2007,Unnamed: 2008,Unnamed: 2009,Unnamed: 2010
0,Throwbacks,False,0,1493424000,52,47,1,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Awesome Playlist,False,1,1506556800,39,23,1,0,Survivor,spotify:track:2HHtWyy5CgaQbC7XSoOb0e,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,korean,False,2,1505692800,64,51,1,0,Hoody,spotify:track:74tqql9zP6JjF5hjkHHUXp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mat,False,3,1501027200,126,107,1,0,Camille Saint-Saëns,spotify:track:4WJ7UMD4i6DOPzyXU5pZSz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,90s,False,4,1401667200,17,16,2,0,The Smashing Pumpkins,spotify:track:4iCGSi1RonREsPtfEKYj5b,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
desired_columns = ['name',
 'collaborative',
 'pid',
 'modified_at',
 'num_albums',
 'num_tracks',
 'num_edits',
 'duration_ms',
 'num_artists',
 'num_followers']

In [5]:
df

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks/0/pos,tracks/0/artist_name,tracks/0/track_uri,...,Unnamed: 2001,Unnamed: 2002,Unnamed: 2003,Unnamed: 2004,Unnamed: 2005,Unnamed: 2006,Unnamed: 2007,Unnamed: 2008,Unnamed: 2009,Unnamed: 2010
0,Throwbacks,False,0,1493424000,52,47,1,0,Missy Elliott,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Awesome Playlist,False,1,1506556800,39,23,1,0,Survivor,spotify:track:2HHtWyy5CgaQbC7XSoOb0e,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,korean,False,2,1505692800,64,51,1,0,Hoody,spotify:track:74tqql9zP6JjF5hjkHHUXp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mat,False,3,1501027200,126,107,1,0,Camille Saint-Saëns,spotify:track:4WJ7UMD4i6DOPzyXU5pZSz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,90s,False,4,1401667200,17,16,2,0,The Smashing Pumpkins,spotify:track:4iCGSi1RonREsPtfEKYj5b,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Feeling Good,False,5995,1426809600,18,16,1,0,Nina Simone,spotify:track:61S0mEfdRtJ62Fc7fPqx0U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,Frost,False,5996,1427068800,67,61,1,0,Slow Magic,spotify:track:4jC2ifws6KbDoXBTkSQiPr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,Kenya,False,5997,1384646400,29,28,2,0,Blood Orange,spotify:track:2iR4oHXi5qsb17b0KHVpon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,17-Aug,False,5998,1504224000,66,64,1,0,Big Sean,spotify:track:1jQsKN68yE94tMYml0wHMd,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,Cardio,False,5999,1506297600,93,53,1,0,Skrillex,spotify:track:5q8oybjZelukF4h0CzSUN9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df[desired_columns]

Data Description
```
name: string
collaborative: boolean -> bit
pid: Number
modified_at: date
num_albums: Number
num_tracks: Number
num_edits: Number
duration_ms: Number
num_artist: Number
num_followers: Number -> Target
```

## Data Cleaning

In [7]:
# Initial types
df.dtypes

name             object
collaborative      bool
pid               int64
modified_at       int64
num_albums        int64
num_tracks        int64
num_edits        object
duration_ms      object
num_artists      object
num_followers     int64
dtype: object

In [8]:
# Type casting the columns
df['name'] = df['name'].astype('str')
df['collaborative'] = df['collaborative'].astype('bool')
df['pid'] = df['pid'].astype('int')

# Date conversions
df['modified_at'] = pd.to_datetime(df['modified_at'], unit='s')
df['year'] = df['modified_at'].dt.year
df['month'] = df['modified_at'].dt.month

# Other numeric conditions
df['num_albums'] = df['num_albums'].astype("int")
df['num_tracks'] = df['num_tracks'].astype("int")

# Will impute the non numeric values to NaN using coerce
df['num_edits'] = pd.to_numeric(df['num_edits'], errors='coerce')
df['duration_ms'] = pd.to_numeric(df['duration_ms'], errors='coerce')
df['num_artists'] = pd.to_numeric(df['num_artists'], errors='coerce')
df['num_followers'] = pd.to_numeric(df['num_followers'], errors='coerce')

C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = df['name'].astype('str')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['collaborative'] = df['collaborative'].astype('bool')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pid'] = df['pid'].astype('int')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['modified_at'] = pd.to_datetime(df['modified_at'], unit='s')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['modified_at'].dt.year
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['modified_at'].dt.month
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_albums'] = df['num_albums'].astype("int")
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_tracks'] = df['num_tracks'].astype("int")
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_edits'] = pd.to_numeric(df['num_edits'], errors='coerce')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['duration_ms'] = pd.to_numeric(df['duration_ms'], errors='coerce')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_artists'] = pd.to_numeric(df['num_artists'], errors='coerce')
C:\Users\hmishra8\AppData\Local\Temp\ipykernel_42980\1149933553.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_followers'] = pd.to_numeric(df['num_followers'], errors='coerce')

In [9]:
# Dropping the column for redundant info
print(df.columns)
df = df.drop(['modified_at'], axis=1)
print(df.columns)

Index(['name', 'collaborative', 'pid', 'modified_at', 'num_albums',
       'num_tracks', 'num_edits', 'duration_ms', 'num_artists',
       'num_followers', 'year', 'month'],
      dtype='object')
Index(['name', 'collaborative', 'pid', 'num_albums', 'num_tracks', 'num_edits',
       'duration_ms', 'num_artists', 'num_followers', 'year', 'month'],
      dtype='object')